# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: 
  version: 
  folders:


  - title: Python Q/A
    output: web, pdf
    folderitems:

    - title: Py MCQ 1-15
      url: /pyQ1.html
      output: web

    - title: Py MCQ 16-30
      url: /pyQ2.html
      output: web, pdf

    - title: Py MCQ 31-45
      url: /pyQ3.html
      output: web, pdf

    - title: Py MCQ 46-60
      url: /pyQ4.html
      output: web, pdf

    - title: Comming Soon
      url: /Comming.html
      output: web, pdf


  - title: Javascript Q/A
    output: web, pdf
    folderitems:

    - title: JS MCQ 1-50
      url: /jsQ50.html
      output: web, pdf

    - title: JS MCQ 51-100
      url: /jsQ100.html
      output: web, pdf

    - title: JS MCQ 101-150
      url: /jsQ150.html
      output: web, pdf




  - title: Comming Soon
    output: web, pdf
    folderitems:

    - title: Comming ....
      url: /Comming.html
      output: web, pdf


