# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Product1
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Python MCQ
    output: web, pdf
    folderitems:
    - title: Py MCQ 1-20
      url: /pyQ1.html
      output: web

    - title: Py MCQ 21-40
      url: /pyQ2.html
      output: web, pdf

    - title: Py MCQ 41-60
      url: /pyQ3.html
      output: web, pdf


  - title: Py Quiz
    output: web, pdf

    folderitems:
    - title: Comming Soon
      url: /Comming.html
      output: web, pdf

    