#!/bin/bash

# bundle update
bundler update

# need to add webrick to the Gemfile
bundle add webrick

# bundle exec jekyll serve
bundler exec jekyll serve

# PATH=$PATH:/home/monadwiz/.local/share/gem/ruby/3.0.0/bin




